-- MySQL Script generated by MySQL Workbench
-- Mon Dec 27 16:46:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_coffee_music
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_coffee_music
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_coffee_music` DEFAULT CHARACTER SET utf8 ;
USE `db_coffee_music` ;

-- -----------------------------------------------------
-- Table `db_coffee_music`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_coffee_music`.`tb_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_coffee_music`.`tb_comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_coffee_music`.`tb_comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comente` VARCHAR(45) NOT NULL,
  `avaliacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_coffee_music`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_coffee_music`.`tb_tema` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_coffee_music`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_coffee_music`.`tb_postagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `texto` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `musica` VARCHAR(45) NOT NULL,
  `tb_usuario_id` INT NOT NULL,
  `tb_tema_id` INT NOT NULL,
  `tb_comentarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_postagens_tb_usuario_idx` (`tb_usuario_id` ASC) VISIBLE,
  INDEX `fk_tb_postagens_tb_tema1_idx` (`tb_tema_id` ASC) VISIBLE,
  INDEX `fk_tb_postagens_tb_comentarios1_idx` (`tb_comentarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagens_tb_usuario`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `db_coffee_music`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagens_tb_tema1`
    FOREIGN KEY (`tb_tema_id`)
    REFERENCES `db_coffee_music`.`tb_tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagens_tb_comentarios1`
    FOREIGN KEY (`tb_comentarios_id`)
    REFERENCES `db_coffee_music`.`tb_comentarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
